---

- hosts: erigam
  become: yes

  vars_files:
  - vars/erigam_docker_env.yml

  roles:
    - build
    - deploy

  handlers:
  - name: reload nginx
    service: name=nginx state=reloaded
    delegate_to: erigam
